# Generated by Django 4.1.4 on 2022-12-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='amt_precipitation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
