# Generated by Django 4.1.4 on 2022-12-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weather_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set(),
        ),
    ]
