# Generated by Django 4.1.4 on 2022-12-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_weather_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
