# Generated by Django 4.1.4 on 2022-12-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_weather_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('date', 'max_temp', 'min_temp', 'amt_precipitation')},
        ),
    ]
